[package]
name = "ds-api-types"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }
semver = { version = "0.9.0", features = ["serde"] }
ssri = "5.0.0"
serde = { version = "1.0.103", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"
serde_json = "1.0.44"
