[package]
name = "ds-package-arg"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
ds-error-context = { path = "../ds-error-context" }

anyhow = "1.0.20"
url = "2.1.0"
semver = "0.9.0"
nom = "5.0.1"
thiserror = "1.0.9"
percent-encoding = "2.1.0"
