[package]
name = "pick-version"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-package-arg = { path = "../../packages/parse-package-arg" }

semver = "0.9.0"
serde_json = "1.0.42"
anyhow = "1.0.25"
ssri = "5.0.0"
chrono = "0.4.10"
thiserror = "1.0.9"

[dev-dependencies]
maplit = "1.0.2"
